In [2]:
from copy import deepcopy
import os
import random
def F128(x):
    t = []
    for i in range(7):
        t.append(x%2)
        x = x//2
    return t
def num(t):
    x = 0
    for i in range(7):
        x = 2*x + t[6-i]
    return x
def rem(a):
    for i in range(6):
        j = 12-i
        x = a[j]
        a[j] = (a[j]+x)%2
        a[j-6] = (a[j-6]+x)%2
        a[j-7] = (a[j-7]+x)%2
        # print(f"{i} : {a}")
    b = [a[i] for i in range(7)]
    return b
def mul(a,b):
    c = []
    for i in range(13):
        x =  0
        for j in range(max(0,i-6),min(6,i)+1):  
            x += a[j]*b[i-j]
        c.append(x%2)
    # print(c)
    return rem(c)
def add(a,b):
    for i in range(7):
        a[i] = (a[i] + b[i])%2
    return a
def exp(a,k):
    if(a==F128(0)):
        return a
    ans = F128(1)
    z = a.copy()
    while k>0:
        if k%2 == 1:
            ans = mul(ans,z)
        z = mul(z,z)
        k = k//2
    return ans


def ascii2e(a):
    res= []
    for i in range(8):
        k = ord(a[2*i])-ord('f')
        k = k*16 + ord(a[2*i+1])-ord('f')
    
        res.append(k)
    return res



def e2ascii(res):
    a = ""
    for i in range(8):
        k = res[i]
        a += chr(ord('f') + k//16)
        a += chr(ord('f') + k%16)
    return a

def getciph (a):
    with open ("text.txt", 'w') as f :
        f.write(e2ascii(a))
    
    ciph = None
    os.system('./shell.sh > out.txt') 
    with open ("out.txt", 'r') as f :
        
        content = f.readlines()
        j=135
        for i in range(0,1):
            ciph = content[j].strip()
    return ascii2e(ciph)

#  dedclare 8x8 matrix
import numpy as np
A_cur = np.zeros((8,8), dtype=int)
# E is 8x1 vector
E_cur = [0]*8

# write matrix multiplication with a vector

def mm(B):
    
    # A is 8x8 matrix
    # B is 8x1 vector
    # C is 8x1 vector
    C = [F128(0) for i in range(8)]
    # print(C)

    for i in range(8):
        for j in range(8):
            aij = F128(A_cur[i][j])
            
            bj = F128(B[j])
            # if(i==1 and j ==0):
            #   print(C[i])
            
            C[i] = add(C[i], mul(aij, bj))
            # if(i==1 and j ==0):
            #     print(aij)
            #     print(bj)

            #     print(C[i])
            #     print('mn')
    
    X= [num(C[i]) for i in range(8)]
    return X

def E(b):
    # b is 8x1 vector
    # c is 8x1 vector
    c = [F128(0)]*8
    for i in range(8):
        c[i] = exp(F128(b[i]), E_cur[i])
    
    X= [num(c[i]) for i in range(8)]
    return X

    
# ak={}
# ek={}

# send =[0]*8


# for i in range (0,8):
#     for reps in range (1,3):
#         x = reps
#         send =[0]*8 
#         send [i] = x
#         o = getciph(send)[i]
#         print(x,o)

#         ta =[]
#         for a in range(0,128):
#             for e in range (1,127):
#                 a1 = F128(a)
#                 x1 = F128(x)
#                 o1 = F128(o)


#                 if( exp(mul (a1, exp(mul(a1,exp(x1,e)),e)),e) == o1 ):
                    
#                     ta.append((a,e))
                    
#         if(i not in ak.keys()):
#                         ak[i] = ta
                        

        
#         ak[i] = list(set(ak[i]).intersection(set(ta)))
#         # ek[i] = list(set(ek[i]).intersection(set(te)))
#         print(i, reps, ak[i])

# print(ak)

akf= {0: [(87, 48), (7, 56), (84, 23)], 1: [(70, 116), (63, 93), (46, 45)], 2: [(17, 106), (43, 39), (15, 109)], 3: [(88, 123), (12, 80), (124, 51)], 4: [(57, 116), (73, 45), (112, 93)], 5: [(97, 61), (86, 16), (11, 50)], 6: [(71, 48), (92, 56), (27, 23)], 7: [(38, 29), (11, 43), (58, 55)]}
# akf = ak
# (aii,e)


# with open ("text.txt", 'w') as f :
#     for i in range(0,8):
#         for j in range (0,128):
#                 temp = [0]* 8 
#                 temp [i]= j
#                 f.write(e2ascii(temp))
#                 f.write('\n')

res={}
# os.system('./shell.sh > out.txt')
with open ("out.txt", 'r') as f :
    content = f.readlines()
    for i in range(0,8):
        res[i] = []
        for j in range(0,128):
            res[i].append(ascii2e(content[135+(i*128 + j )*17].strip()))




memoryyy ={}

for i in range(0,7):
    print(i)
    found =0

    
    for a in range(0,128):
        if(found):
            break
        p1 = akf[i]
        p2 = akf[i+1]
        for x in p1 : 
            for y in p2 :
                flag =1
                if(found ):
                    break

                for reps in range(0,128):
                    # x = reps
                    send =[0]*8
                    send [i] = reps
                    o = res[i][reps][i+1]
                    o1 = res[i][reps][i]
                    # assert(o == getciph(send)[i+1])
                    E_cur[i] = x[1]
                    E_cur[i+1] = y[1]
                    A_cur[i][i] = x[0]
                    A_cur[i+1][i+1] = y[0]
                    A_cur[i+1][i] = a

                    # print(reps, x,y,a)

                    # simulate  E matmul E matmul E
                    if(E(mm(E(mm(E(send)))))[i] != o1):
                        
                        print('not gg')
                        print(o1, E(mm(E(mm(E(send)))))[i], reps, i,x,y,a)
                        #  debug
                        print(send)

                        print(E(send))
                        print(A_cur)
                        print(E(send))

                        print(mm(E(send)))

                        print(E(mm(E(send))))
                        print(mm(E(mm(E(send)))))
                        print(E(mm(E(mm(E(send))))))
                        
                        

                        print(num(exp(F128(87), 48*49)))
                        exit()
                    if( E(mm(E(mm(E(send)))))[i+1] == o):
                        continue
                    else :
                        flag= 0 
                        break
                
                if(flag == 1):
                    found =1
                    print(a,x,y)


  





    
                


0
119 (84, 23) (70, 116)
1
31 (70, 116) (43, 39)
2
26 (43, 39) (12, 80)
3
122 (12, 80) (112, 93)
4
97 (112, 93) (11, 50)
5
89 (11, 50) (27, 23)
6
29 (27, 23) (38, 29)


In [3]:
backup = A_cur.copy()


In [4]:
back2  = E_cur.copy()


In [5]:
print(backup)
print(back2)

[[ 84   0   0   0   0   0   0   0]
 [119  70   0   0   0   0   0   0]
 [  0  31  43   0   0   0   0   0]
 [  0   0  26  12   0   0   0   0]
 [  0   0   0 122 112   0   0   0]
 [  0   0   0   0  97  11   0   0]
 [  0   0   0   0   0  89  27   0]
 [  0   0   0   0   0   0  29  38]]
[23, 116, 39, 80, 93, 50, 23, 29]


In [6]:
for d in range(2,8):
    for i in range(d,8):
        found =0
        for a in range(0,128):
            if(found):
                break
            flag =1 
            for reps in range(1,128):
                A_cur[i][i-d] = a
                send =[0]*8
                send [i-d] = reps
                o = res[i-d][reps][i]

                o1 = res[i-d][reps][i-1]
                # print(i,i-d, a, reps, E(mm(E(mm(E(send)))))[i], o)
                # print("FK")

                # print(num(exp(
                #     add(
                #     mul(F128(A_cur[2][0]), exp(mul(F128(A_cur[0][0]), F128(reps)),E_cur[0])),
                #     add(mul(F128(A_cur[2][1]), exp(mul(F128(A_cur[1][0]), F128(reps)),E_cur[1])),         
                #            mul(F128(A_cur[2][2]), exp(mul(F128(A_cur[2][0]), F128(reps)),E_cur[2])))), E_cur[2])))
                # print(E(mm(E(mm(E(send)))))[i])
                # print(o)


                if( E(mm(E(mm(E(send)))))[i-1] != o1):
                    assert(0)


                if( E(mm(E(mm(E(send)))))[i] == o):
                    continue
                else :
                    flag= 0 
                    break
            
            if(flag == 1):
                found =1
                print(i,i-d, a)
                # memoryyy [i-d]=(a,memoryyy[i-d][1],memoryyy[i-d][2])



2 0 12
3 1 17
4 2 13
5 3 47
6 4 2
7 5 70
3 0 125
4 1 57
5 2 28
6 3 102
7 4 24
4 0 98
5 1 49
6 2 22
7 3 23
5 0 29
6 1 124
7 2 77
6 0 5
7 1 14


In [ ]:
print(A_cur)

[[ 84   0   0   0   0   0   0   0]
 [119  70   0   0   0   0   0   0]
 [ 12  31  43   0   0   0   0   0]
 [125  17  26  12   0   0   0   0]
 [ 98  57  13 122 112   0   0   0]
 [ 29  49  28  47  97  11   0   0]
 [  5 124  22 102   2  89  27   0]
 [127  14  77  23  24  70  29  38]]


In [ ]:
count =0

send = [0] * 8 

password = "msfhjqifisinlogrgtjsjmkumfkrjlfs"

# passw2 = [password[i:i+8] for i in range(0, len(password), 8)]

passw = [ascii2e("msfhjqifisinlogr"), ascii2e("gtjsjmkumfkrjlfs")]


while( count != 8 ):

    for i in range (0,128):

        send [count] = i
        if(getciph(send) != E(mm(E(mm(E(send)))))):
            print(send)
            print(getciph(send))
            print(E(mm(E(mm(E(send))))))

        if(E(mm(E(mm(E(send)))))[count] == passw[0][count]):
            count +=1
            break

count =0


print(''.join([chr(x) for x in send]))
print(send)
send = [0] * 8 

while( count != 8 ):

    for i in range (0,128):

        send [count] = i
        if(E(mm(E(mm(E(send)))))[count] == passw[1][count]):
            count +=1
            break


print(''.join([chr(x) for x in send]))
print(send)

[0, 0, 0, 0, 0, 0, 0, 0]
[97, 0, 0, 0, 0, 0, 0, 0]
